# ───────────────────────── Common baseline ──────────────────────────
- import_playbook: debian_linux.yml   # <- targets group [debian] or all

# ───────────────────────── Laptop-specific ──────────────────────────
- import_playbook: msi_laptop.yml     # <- hosts: msi_laptop

# ───────────────────────── K3s Controller ───────────────────────────
- import_playbook: k3s_controller.yml # <- hosts: k3s_controller
